[package]
name = "kaon"
version = "0.1.0"
authors = ["Davis Van Sant <davisvansant@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.hyper]
version = "0.14.2"
default_features = false
features = [ "client", "http1", "tcp" ]

[dependencies.tracing]
version = "0.1.22"
default_features = false
features = [ "std", "attributes" ]

[dependencies.tracing-futures]
version = "0.2.4"
default_features = false
features = [ "std-future", "std" ]

[dev-dependencies.tokio]
version = "1.1.0"
default_features = false
features = [ "rt", "macros", "test-util" ]

[dev-dependencies.tracing-subscriber]
version = "0.2.15"
default_features = false
features = [ "default" ]
